repos:
  - repo: local
    hooks:
      - id: update-readme
        name: update-readme
        entry: task generate
        language: system
        pass_filenames: false

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-mod-tidy
