version: '3'

includes:
  build-xair:
    taskfile: ./Taskfile.build-xair.yml
    internal: true
    vars:
      PROGRAM: xair-cli
  build-x32:
    taskfile: ./Taskfile.build-x32.yml
    internal: true
    vars:
      PROGRAM: x32-cli

vars:
  SHELL: '{{if eq .OS "Windows_NT"}}powershell{{end}}'
  BIN_DIR: bin
  VERSION:
    sh: 'git describe --tags $(git rev-list --tags --max-count=1)'

tasks:
  default:
    desc: Build the xair-cli and x32-cli projects for all platforms
    cmds:
      - task: build

  build:
    desc: Build the xair-cli and x32-cli projects for all platforms
    deps: [vet]
    cmds:
      - for:
          matrix:
            PROGRAM: ['build-xair', 'build-x32']
            TARGET: ['windows-amd64', 'linux-amd64', 'darwin-amd64']
        task: '{{.ITEM.PROGRAM}}:{{.ITEM.TARGET}}'

  vet:
    desc: Vet the code
    deps: [fmt]
    cmds:
      - go vet ./...

  fmt:
    desc: Fmt the code
    cmds:
      - go fmt ./...

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Clean the build artifacts
    cmds:
      - '{{.SHELL}} rm -r {{.BIN_DIR}}'
